-- BIZAI TZ production database starter (Supabase/Postgres)
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  tokens integer not null default 30,
  created_at timestamptz not null default now()
);

create table if not exists token_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references profiles(id) on delete cascade,
  amount integer not null,
  type text not null, -- purchase, usage, bonus, refund
  reference text,
  created_at timestamptz not null default now()
);

create table if not exists generations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references profiles(id) on delete cascade,
  service text not null,
  tokens_used integer not null,
  output text,
  created_at timestamptz not null default now()
);

-- IMPORTANT: In production, token changes should happen through
-- server-side functions/RPC with authorization, not directly from the browser.
